# Generated by Django 4.2.1 on 2024-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian')], default='english', max_length=10)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('good', 'Good'), ('fluent', 'Fluent')], default='basic', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(upload_to='photos/')),
                ('photo2', models.ImageField(upload_to='photos/')),
                ('photo3', models.ImageField(upload_to='photos/')),
                ('photo4', models.ImageField(upload_to='photos/')),
                ('photo5', models.ImageField(upload_to='photos/')),
                ('orientation', models.CharField(max_length=50)),
                ('ethnicity', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('smokes', models.BooleanField()),
                ('nationality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('height_cm', models.PositiveIntegerField()),
                ('bust_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('shaved', models.BooleanField()),
                ('hair_color', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('incalls_cost', models.DecimalField(decimal_places=2, help_text='Cost for incalls per hour in currency.', max_digits=10)),
                ('outcalls_cost', models.DecimalField(decimal_places=2, help_text='Cost for outcalls per hour in currency.', max_digits=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('languages', models.ManyToManyField(related_name='escorts', to='escorts.language')),
            ],
        ),
    ]
