# Generated by Django 4.2.1 on 2024-09-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0002_nationality_alter_escort_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationality',
            name='name',
        ),
        migrations.AddField(
            model_name='nationality',
            name='nationality',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escort',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escorts.nationality'),
        ),
    ]
