# Generated by Django 4.2.1 on 2024-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0003_remove_nationality_name_nationality_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
