# Generated by Django 4.2.1 on 2024-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0004_alter_escort_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationality',
            old_name='nationality',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='escort',
            name='incalls_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='escort',
            name='outcalls_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
