# Generated by Django 4.2.1 on 2024-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escorts', '0005_rename_nationality_nationality_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='bust_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='escort',
            name='ethnicity',
            field=models.CharField(choices=[('Asian', 'Asian'), ('Black', 'Black'), ('Caucasian', 'Caucasian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='escort',
            name='hair_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Blonde', 'Blonde')], max_length=50),
        ),
        migrations.AlterField(
            model_name='escort',
            name='orientation',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Gay', 'Gay'), ('Bisexual', 'Bisexual')], max_length=50),
        ),
    ]
